### ISSUE TITLE
No API for `turnFlagOn`?

### ISSUE THREAD

**Issue by scowalt** [launchdarkly/api-client-typescript#4]
Using the REST api over HTTPs, you can make the following request:

```ts
 const requestInfo = {
      hostname: `app.launchdarkly.com`,
      path: `/api/v2/flags/${projectKey}/${flagKey}`,
      method: 'PATCH',
      headers: {
        Authorization: LAUNCHDARKLY_ACCESS_TOKEN,
        'Content-Type': 'application/json; domain-model=launchdarkly.semanticpatch',
      },
    };
 const requestBody = {
      environmentKey,
      instructions: [{ kind: 'turnFlagOn' }],
    };
do_request(requestInfo, requestBody);
```

See the [`patchFeatureFlag` REST API docs](https://apidocs.launchdarkly.com/tag/Feature-flags#operation/patchFeatureFlag)

I couldn't find this functionality exposed on the `FeatureFlagsApi` object in this API. Is that an accidental omission? Or did I miss it somewhere?

**Comment by carmenquan** [comment]
Hi @scowalt, let me follow up with our team and get a response for you this week, with some sample code on how to accomplish this. Thanks!

**Comment by carmenquan** [comment]
Hi @scowalt,

While our REST APIs support both semantic patch and JSON patch for the `patchFeatureFlag` endpoint, unfortunately, in our client libraries we are unable to support both. For this particular endpoint, we only support JSON patch. Here's a code snippet for how you can turn on a flag using our client library and JSON patch.

```javascript
let patch = new LaunchDarklyApi.PatchOperation('replace', '/environments/' + envKey + '/on', true);
let patchWithComment = new LaunchDarklyApi.PatchWithComment([patch]);
apiInstance.patchFeatureFlag(projectName, keyName, patchWithComment, (error, data, response) => {
  if (error) {
    console.error(error);
  } else {  
    console.log('API called successfully. Returned data: ' + data);
  }
});
```
Feel free to reach out if you have additional questions or feedback - thanks!
Carmen

**Comment by scowalt** [comment]
Thank you so much for the reply Carmen! I'll try this out and reopen if I'm still getting stuck

**Comment by scowalt** [comment]
Just to follow-up, I was able to figure out `turnFlagOn` with JSON patching in the TypeScript API:

```ts
  const patch: PatchOperation = {
    op: 'replace',
    path: `/environments/${environment}/on`,
    value: true,
  };
  const patchWithComment: PatchWithComment = { patch: [patch] };
  await apiInstance.patchFeatureFlag(PROJECT_KEY, feature_flag_key, patchWithComment);
```

Thanks again! I have a better understanding of how JSON patching works now

**Comment by carmenquan** [comment]
Sorry @scowalt, I misread and did testing in our javascript client 🤦‍♀️  glad you got it working though!
