### ISSUE TITLE
Reached heap limit Allocation failed - error

### ISSUE THREAD

**Issue by juandanceswild** [launchdarkly/api-client-typescript#6]
I'm using this library in a Node project but at the time of building it in my server it fails with a `Javascript out of memory` message. 

It seems to happen as soon as I create an apiInstance

`const apiInstance = new FeatureFlagsApi(config);`

For now I will have to refactor and deploy code using the fetch api to interact with the LaunchDarkly API directly.

**Comment by ldhenry** [comment]
Hey @juandanceswild,

Thanks for bringing this to our attention. I've created an internal ticket to track this and we'll be sure to update this issue as we learn more.

Thanks,
Henry

**Comment by lucywyman** [comment]
Hi @juandanceswild I'm having trouble reproducing this issue. Are there other Javascript libraries that you can successfully use on this machine? Is it a deployed application, or a standalone script?

You might also try [increasing the memory limit for Node](https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory) depending on how you're running the file.

**Comment by lucywyman** [comment]
Hi @juandanceswild , I'm going to close this issue as we're having trouble reproducing it. Let me know if you're able to resolve the issue, or can provide more information that can help us look further into this!
